hydra:
  job:
    chdir: False

train_summary_file: "../data/summaries_train.csv"
train_prompt_file : "../data/prompts_train.csv"
batch_size: 16
epochs: 4
lr: 2e-5
max_len: 768
model_name: "microsoft/deberta-v3-large"
hidden_dropout_prob: 0.1
layer_norm_eps: 1e-7
gradient_accumulation_steps: 4
gradient_checkpointing_enable: False
warmup_ratio: 0.1
max_grad_norm: 10.0
target_columns: ['content', 'wording']
num_classes: 2
seed: 42
device: "cuda"
multi_gpu: False
use_wandb: True
project_name: "commonlit-kaggle"
output_dir: "../output/"
repo_id: ""
freeze: True 
start_freeze_layer: 0
end_freeze_layer: 12
llrd: 1
train_whole_dataset: False
correct_spelling: False
use_prompt_text: True
columns_to_use: ["text", "prompt_text"]
criterion: "mcrmse"
use_gpl_checkpoint: True 
gpl_repo_id: "jashdalvi/commonlit-kaggle-gpl-deberta-v3-large"